apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
configMapGenerator:
- name: statefulset-params
  envs: [params.env]
secretGenerator:
- name: statefulset-secrets
  envs: [secrets.env]
resources:
- storage-class.yaml